version: '3.7'

volumes:
  diamond-data:
  diamond-models:

services:
  diamonds-api:
    build: 
      context: /diamonds
      dockerfile: Dockerfile
    volumes:
      - diamond-data:/app/data
      - diamond-models:/app/models
    expose:
      - "5000"

  diamonds-dashboard:
    build: 
      context: /dashboard
      dockerfile: Dockerfile
    volumes:
      - diamond-data:/app/data
      - diamond-models:/app/models
    expose:
      - "9050"
    depends_on:
      - diamonds-api
      
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - diamonds-api
      - diamonds-dashboard